Fix compilation with -Werror
Fix this warning (which is error with -Werror):

java_bytecode/remove_instanceof.cpp:258:10: error: use of bitwise '|' with boolean operands [-Werror,-Wbitwise-instead-of-logical]