unit/util/string_utils/: Fix compilation on platforms where char is unsigned
Caused following error on ARMv7hl, aarch64, ppc64le, s390x:

FAILED: unit/CMakeFiles/unit.dir/util/string_utils/escape_non_alnum.cpp.o
../unit/util/string_utils/escape_non_alnum.cpp:158:68: error: narrowing conversion of '-128' from 'signed char' to 'char' [-Wnarrowing]
  158 |   CHECK(escape_non_alnum(std::string{static_cast<signed char>(0x80)}) == "_80");
      |